spring:
  cloud:
    gateway:
      routes:
       - id: gulimall-member
         uri: lb://gulimall-member
         predicates:
            - Path=/api/member/**
         filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

       - id: product_route
         uri: lb://gulimall-product
         predicates:
            - Path=/api/product/**
         filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

       - id: third_party_route
         uri: lb://gulimall-third-party
         predicates:
            - Path=/api/thirdparty/**
         filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

       - id: admin_route
         uri: lb://renren-fast # 路由给renren-fast，lb代表负载均衡
         predicates:  # 什么情况下路由给它
            - Path=/api/** # 默认前端项目都带上api前缀，
         filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

