spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: access-key
      secret-key: secret-key
      oss:
         endpoint: oss-cn-beijing.aliyuncs.com
         bucket: gulimall-cyg
  application:
    name: gulimall-third-party
server:
  port: 30000